name: Verify Dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt,clippy

      - name: Run rustfmt
        run: cargo fmt -- --check

      - name: Run clippy
        if: always()
        run: cargo clippy -- -D warnings

      - name: Run tests
        if: always()
        run: cargo test
